version: '3.9'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - postgres-net
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  app:
    build:
      context: .
    ports:
      - 5000:80
    depends_on:
      - db
    networks:
      - postgres-net
volumes:
  postgres-data:
networks:
  postgres-net:
    external: true
